// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5xzkBeXKjFySiCMFNTuG0M8SFx30cBI',
    appId: '1:340297612971:web:c8fbed7d0686eae45141ee',
    messagingSenderId: '340297612971',
    projectId: 'fintechwallet-bbaca',
    authDomain: 'fintechwallet-bbaca.firebaseapp.com',
    storageBucket: 'fintechwallet-bbaca.firebasestorage.app',
    measurementId: 'G-NFVMGM7JLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNogCIByjpzt4puMTkutJMk25Rp-C-7EM',
    appId: '1:340297612971:android:56c58704cccf5b2e5141ee',
    messagingSenderId: '340297612971',
    projectId: 'fintechwallet-bbaca',
    storageBucket: 'fintechwallet-bbaca.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClkyLsqUfOmBQHIqTC5Cyf1hl0hFwuFPg',
    appId: '1:340297612971:ios:810f8a39fa73bf8c5141ee',
    messagingSenderId: '340297612971',
    projectId: 'fintechwallet-bbaca',
    storageBucket: 'fintechwallet-bbaca.firebasestorage.app',
    iosBundleId: 'com.example.fintechWallet',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClkyLsqUfOmBQHIqTC5Cyf1hl0hFwuFPg',
    appId: '1:340297612971:ios:810f8a39fa73bf8c5141ee',
    messagingSenderId: '340297612971',
    projectId: 'fintechwallet-bbaca',
    storageBucket: 'fintechwallet-bbaca.firebasestorage.app',
    iosBundleId: 'com.example.fintechWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_5xzkBeXKjFySiCMFNTuG0M8SFx30cBI',
    appId: '1:340297612971:web:9c44e5be09ffd0725141ee',
    messagingSenderId: '340297612971',
    projectId: 'fintechwallet-bbaca',
    authDomain: 'fintechwallet-bbaca.firebaseapp.com',
    storageBucket: 'fintechwallet-bbaca.firebasestorage.app',
    measurementId: 'G-XCN3QPWGK0',
  );
}
